In [5]:
import torch

x = torch.FloatTensor(4) # 4개의 입력
W = torch.FloatTensor(4, 3) # (4, 3) 행렬 가중치
b = torch.FloatTensor(3) # 3개의 출력

In [6]:
def linearfunction(x, W, b):
    y = torch.matmul(x, W) + b
    return y
# (1, 4) x (4, 3) = (3, )
# (3, ) + (3, ) = (3, )

In [7]:
print('W', W.shape, 'x', x.shape, 'b', b.shape)

W torch.Size([4, 3]) x torch.Size([4]) b torch.Size([3])


In [8]:
y = linearfunction(x, W, b)
y.shape

torch.Size([3])

In [13]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self):
        # super() 함수는 super(subclass 이름, subclass 객체).__init__()와 같이 써야 하지만
        # 하부클래스 선언 내부에서 super()호출 시는 super().__init__()와 같이 쓰면 자동으로 두인자가 넣어져서 호출됨
        super().__init__()
        # __init__()에서 신경망 계층 초기화
        self.W = torch.FloatTensor(4, 3)
        self.b = torch.FloatTensor(3)

    def forward(self, x):
        # |x| = (input_dim)
        # |y| = (input_dim) * (input_dim, output_dim) + (output_dim)
        #     = (output_dim)
        y = torch.matmul(x, self.W) + self.b
        return y

In [14]:
x = torch.FloatTensor(4)
mylinear = NeuralNetwork()
# forward에 넣을 인자값으로 호출하면 내부적으로 forward() 메소드를 자동 호출함(정석)
# 내부 처리 중, forward() 전처리/후처리도 수행하므로 forward()를 직접 호출하면 전처리/후처리를 수행하지 않게 될 수 있음
y = mylinear(x)

In [15]:
print(y, y.shape)

tensor([0., 0., 0.]) torch.Size([3])


In [16]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim):
        # super() 함수는 super(subclass 이름, subclass 객체).__init__()와 같이 써야 하지만
        # 하부클래스 선언 내부에서 super()호출 시는 super().__init__()와 같이 쓰면 자동으로 두인자가 넣어져서 호출됨
        super().__init__()
        # __init__()에서 신경망 계층 초기화
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)

    def forward(self, x):
        # |x| = (input_dim)
        # |y| = (input_dim) * (input_dim, output_dim) + (output_dim)
        #     = (output_dim)
        y = torch.matmul(x, self.W) + self.b
        return y

In [20]:
x = torch.FloatTensor(15)
mylinear = NeuralNetwork(15, 5)
y = mylinear(x)
print(y, y.shape)

tensor([0., 0., 0., 0., 0.]) torch.Size([5])


In [21]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim):
        # super() 함수는 super(subclass 이름, subclass 객체).__init__()와 같이 써야 하지만
        # 하부클래스 선언 내부에서 super()호출 시는 super().__init__()와 같이 쓰면 자동으로 두인자가 넣어져서 호출됨
        super().__init__()
        # __init__()에서 신경망 계층 초기화
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))

    def forward(self, x):
        # |x| = (input_dim)
        # |y| = (input_dim) * (input_dim, output_dim) + (output_dim)
        #     = (output_dim)
        y = torch.matmul(x, self.W) + self.b
        return y

In [22]:
x = torch.FloatTensor(15)
mylinear = NeuralNetwork(15, 5)
y = mylinear(x)
print(y, y.shape)
for param in mylinear.parameters():
    print(param)

tensor([0., 0., 0., 0., 0.], grad_fn=<AddBackward0>) torch.Size([5])
Parameter containing:
tensor([[5.0786e-35, 1.7432e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],

In [24]:
mylinear = nn.Linear(15, 3)
y = mylinear(x)
print(y, y.shape)

for param in mylinear.parameters():
    print(param)

tensor([-0.1438,  0.1331, -0.1704], grad_fn=<ViewBackward0>) torch.Size([3])
Parameter containing:
tensor([[-0.1671, -0.0928, -0.1145,  0.2287,  0.2371,  0.2121, -0.1970,  0.1631,
         -0.0451,  0.0249,  0.1258,  0.1374,  0.0985, -0.1436,  0.0942],
        [ 0.0918, -0.0025,  0.0670, -0.1604, -0.1696,  0.1433, -0.0793,  0.0577,
         -0.2348,  0.0229, -0.1275,  0.1239, -0.0147, -0.1806, -0.0852],
        [-0.2423,  0.1041, -0.2130, -0.0402,  0.0351, -0.0095, -0.1578, -0.1970,
         -0.0960,  0.2460,  0.2218, -0.0343,  0.1000,  0.0886,  0.2424]],
       requires_grad=True)
Parameter containing:
tensor([-0.1438,  0.1331, -0.1704], requires_grad=True)
