In [3]:
import torch

A = torch.full((3, ), 2)
B = torch.full((3, ), 3)
print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)
result = torch.matmul(A, B)
print(result, result.shape)
# 1D 텐서(벡터)끼리의 곱셉 = 스칼라

tensor([2, 2, 2]) 1 torch.Size([3])
tensor([3, 3, 3]) 1 torch.Size([3])
tensor(18) torch.Size([])


In [5]:
A = torch.full((3, 2), 2)
B = torch.full((2, 3), 3)
print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)
result = torch.matmul(A, B)
print(result, result.shape)
# 2D 텐서(행렬)끼리의 곱셈 = 3, 2 x 2, 3 = 3, 3

tensor([[2, 2],
        [2, 2],
        [2, 2]]) 2 torch.Size([3, 2])
tensor([[3, 3, 3],
        [3, 3, 3]]) 2 torch.Size([2, 3])
tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]]) torch.Size([3, 3])


In [8]:
x = torch.full((3, ), 2)
B = torch.full((3, 2), 3)
print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)
result = torch.matmul(x, B)
print(result, result.shape)
# 1D 텐서(벡터)와 2D 텐서(행렬)의 곱셈은 벡터로 출력됨, (1, 2) or (2, 1) 아님 (2, )
# 기본적으로 벡터는 열벡터, 이것을 행벡터로 트랜스포즈하고
# 1, 3 x 3, 2 = 1, 2 = 2

tensor([[2, 2],
        [2, 2],
        [2, 2]]) 2 torch.Size([3, 2])
tensor([[3, 3],
        [3, 3],
        [3, 3]]) 2 torch.Size([3, 2])
tensor([18, 18]) torch.Size([2])


In [13]:
x = torch.full((3, ), 2)
B = torch.full((4, 3, 2), 3)
print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)
result = torch.matmul(x, B)
print(result, result.shape)
# 3D 이상 텐서는 batched matrix로 간주하여 --- b x (c, d)
# b x (a x (c, d)) = b x d
# = (b, d)

tensor([[2, 2],
        [2, 2],
        [2, 2]]) 2 torch.Size([3, 2])
tensor([[[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]]]) 3 torch.Size([4, 3, 2])
tensor([[18, 18],
        [18, 18],
        [18, 18],
        [18, 18]]) torch.Size([4, 2])


In [14]:
B = torch.full((3, 2), 3)
x = torch.full((2, ), 2)
print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)
result = torch.matmul(B, x)
print(result, result.shape)
# 2D x 1D는 3, 2 x 2, 1 = 3, 1 = 3개 원소의 벡터

tensor([[2, 2],
        [2, 2],
        [2, 2]]) 2 torch.Size([3, 2])
tensor([[3, 3],
        [3, 3],
        [3, 3]]) 2 torch.Size([3, 2])
tensor([12, 12, 12]) torch.Size([3])


In [15]:
B = torch.full((4, 3, 2), 3)
x = torch.full((2, ), 2)
print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)
result = torch.matmul(B, x)
print(result, result.shape)
# 3D x 1D는 4 x ((3, 2) x (2)) = 4 x 3 = 4, 3

tensor([[2, 2],
        [2, 2],
        [2, 2]]) 2 torch.Size([3, 2])
tensor([[[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]]]) 3 torch.Size([4, 3, 2])
tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]]) torch.Size([4, 3])


In [20]:
data1 = torch.full((10, 1, 3, 4), 2)
data2 = torch.full((2, 4, 5), 3)

print(data1.dim(), data1.shape)
print(data2.dim(), data2.shape)
data3 = torch.matmul(data1, data2)
print(data3.shape)

data4 = torch.full((10, 8, 3, 4), 2)
data5 = torch.full((1, 8, 4, 5), 3)

print(data4.dim(), data4.shape)
print(data5.dim(), data5.shape)
data6 = torch.matmul(data4, data5)
print(data6.shape)
# 3D 이상 텐서의 곱셈
# (b, m, n) x (b, n, k)
# = (m, n) x (n, k) = (m, k)
# = (b, m, k)
# 마지막 두개 차원 이외의 앞 부분은 브로드캐스팅 룰이 적용됨

4 torch.Size([10, 1, 3, 4])
3 torch.Size([2, 4, 5])
torch.Size([10, 2, 3, 5])
4 torch.Size([10, 8, 3, 4])
4 torch.Size([1, 8, 4, 5])
torch.Size([10, 8, 3, 5])


In [23]:
data1 = torch.full((3, 4), 2)
data2 = torch.full((4, 5), 3)

print(data1.dim(), data1.shape)
print(data2.dim(), data2.shape)
data3 = torch.mm(data1, data2)
print(data3.shape)
# mm()은 2D 행렬곱만 지원함

2 torch.Size([3, 4])
2 torch.Size([4, 5])
torch.Size([3, 5])


In [24]:
data1 = torch.full((2, 3, 4), 2)
data2 = torch.full((2, 4, 5), 3)

print(data1.dim(), data1.shape)
print(data2.dim(), data2.shape)
data3 = torch.bmm(data1, data2)
print(data3.shape)
# bmm()은 3D 행렬곱만 지원함
# 브로드캐스팅은 지원하지 않음

3 torch.Size([2, 3, 4])
3 torch.Size([2, 4, 5])
torch.Size([2, 3, 5])
