# Adam optimizer 테스트

In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.ones(5000, 10)
y = torch.zeros(5000, 1)
learning_rate = 0.01
nb_epochs = 1000
minibatch_size = 256

In [4]:
input_dim = x.size(-1)
output_dim = y.size(-1)

model = nn.Sequential(
    nn.Linear(input_dim, 10),
    nn.LeakyReLU(0.1),
    nn.Linear(10, 8),
    nn.LeakyReLU(0.1),
    nn.Linear(8, 6),
    nn.LeakyReLU(0.1),
    nn.Linear(6, output_dim)
)

loss_function = nn.MSELoss()
# optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
# optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum=0.9)
# optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum=0.9, nesterov=True)
# optimizer = torch.optim.Adagrad(model.parameters())
# optimizer = torch.optim.RMSProp(model.parameters())
optimizer = torch.optim.Adam(model.parameters())

In [5]:
indices = torch.randperm(x.size(0)) # 5000개의 인덱스 번호를 만들어서 섞음
print(indices)
x_batch_list = torch.index_select(x, 0, index=indices) # indices로 데이터셋을 shuffle
y_batch_list = torch.index_select(y, 0, index=indices)

y_batch_list[0].shape
x_batch_list = x_batch_list.split(minibatch_size, dim=0) # 행을 기준으로 미니배치 사이즈로 나눈다
y_batch_list = y_batch_list.split(minibatch_size, dim=0)
print(len(x_batch_list), len(y_batch_list))
type(y_batch_list)
type(y_batch_list[0])
x_batch_list[0]

tensor([1490,  101,  102,  ..., 4758, 4770,  138])
20 20


tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [6]:
for index in range(nb_epochs):
    indices = torch.randperm(x.size(0))

    x_batch_list = torch.index_select(x, 0, index=indices)
    y_batch_list = torch.index_select(y, 0, index=indices)
    x_batch_list = x_batch_list.split(minibatch_size, dim=0)
    y_batch_list = y_batch_list.split(minibatch_size, dim=0)

    for x_minibatch, y_minibatch in zip(x_batch_list, y_batch_list):
        y_minibatch_pred = model(x_minibatch)
        loss = loss_function(y_minibatch_pred, y_minibatch)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

print(loss)
for param in model.parameters():
    print(param)

tensor(0., grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[-0.1417,  0.3198,  0.3355,  0.1921,  0.2131, -0.0885,  0.2643,  0.1967,
         -0.1762, -0.0375],
        [ 0.0787,  0.1616,  0.1084,  0.0222, -0.1283,  0.2333,  0.1093, -0.1905,
          0.2983, -0.2375],
        [ 0.2424,  0.0665,  0.2803, -0.0501, -0.1975, -0.0855,  0.0017,  0.2472,
          0.1301,  0.0772],
        [-0.0176,  0.2423,  0.0262,  0.3480,  0.0447, -0.0114, -0.0440,  0.1532,
         -0.0663, -0.2149],
        [-0.1264, -0.0482,  0.2372,  0.0767,  0.1848,  0.0672, -0.0676,  0.3747,
         -0.0272, -0.0268],
        [-0.2902,  0.2761,  0.2390,  0.0976, -0.0946,  0.1325,  0.0688, -0.1946,
         -0.3034,  0.0754],
        [ 0.0590,  0.0710, -0.1050, -0.0883, -0.0418, -0.0112,  0.0321, -0.2028,
         -0.1169, -0.0850],
        [ 0.1712, -0.0594,  0.3115, -0.0378, -0.0564,  0.2242, -0.1159, -0.0715,
          0.3644,  0.0132],
        [ 0.0833, -0.1770,  0.2076,  0.2870,  0.0865,  0.2605,  0.0