In [3]:
data1 = [1, 2, 3]
data2 = [4, 5, 6]
data1+data2

[1, 2, 3, 4, 5, 6]

In [5]:
import numpy as np

data1 = np.array([1, 2, 3])
print(data1, type(data1))

[1 2 3] <class 'numpy.ndarray'>


In [7]:
data1.shape

(3,)

In [8]:
data1.ndim

1

In [9]:
data2 = np.array([ [1,2, 3], [4, 5, 6] ])
print(data2.shape, data2.ndim)

(2, 3) 2


In [10]:
print(data1.dtype, data2.dtype)

int32 int32


In [11]:
print(data1.size, data2.size)

3 6


In [12]:
data3 = np.array([ [1., 2., 3.], [4., 5., 6.] ])
print(data3.shape, data3.ndim, data3.dtype, data3.size)

(2, 3) 2 float64 6


In [13]:
data3 = np.array([1, 2, 3, 4, 5, 6])
print(data3)
data3 = data3.reshape(3, 2)
print(data3)
data3 = data3.reshape(3, -1)
print(data3)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [17]:
data4 = np.array([ [1, 2, 3], [4, 5, 6] ], dtype=np.float64)
print(data4.shape, data4.ndim, data4.dtype, data4.size)

(2, 3) 2 float64 6


In [18]:
data4 = np.float64([ [1, 2, 3], [4, 5, 6] ])
print(data4.shape, data4.ndim, data4.dtype, data4.size)

(2, 3) 2 float64 6


In [19]:
data4 = np.array([ [1, 2, 3], [4, 5, 6] ], dtype='f8')
print(data4.shape, data4.ndim, data4.dtype, data4.size)

(2, 3) 2 float64 6


In [21]:
data4 = np.array([ [1, 2, 3], [4, 5, 6] ], dtype='f8')
print(data4.shape, data4.ndim, data4.dtype, data4.size)
data4 = data4.astype(np.int64)
print(data4.shape, data4.ndim, data4.dtype, data4.size)

(2, 3) 2 float64 6
(2, 3) 2 int64 6


In [22]:
data4 = np.float64([ [1, 2, 3], [4, 5, 6] ])
print(data4)
data4 = data4.T
print(data4)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 4.]
 [2. 5.]
 [3. 6.]]


In [25]:
data = np.arange(6).reshape(1, 2, 3)
print(data, data.shape)
print(np.transpose(data), np.transpose(data).shape)
print(np.transpose(data, (1, 2, 0)), np.transpose(data, (1, 2, 0)).shape)
# 여러개의 축(차원)을 변경
# 원하는 인덱스로 축을 구성할 수도 있음

[[[0 1 2]
  [3 4 5]]] (1, 2, 3)
[[[0]
  [3]]

 [[1]
  [4]]

 [[2]
  [5]]] (3, 2, 1)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


In [26]:
np.arange(5)
np.arange(1, 5)
np.arange(1, 5, 2)

array([1, 3])

In [27]:
np.linspace(1, 5, 4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [28]:
np.zeros(shape=(2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones(shape=(3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
np.full(shape=(4, 2), fill_value=5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [32]:
print(np.random.rand(3, 2))
print(np.random.randn(3, 2))

[[0.88390154 0.42629927]
 [0.24847486 0.47785315]
 [0.31389909 0.09657363]]
[[ 2.07853067 -0.18850925]
 [ 0.06085731  1.38964142]
 [-0.21892014  1.48068319]]


In [33]:
data1 = np.array([ [1, 2, 3], [4, 5, 6] ])
data2 = np.array([ [1, 2, 3], [4, 5, 6] ])
print(data1+data2)
print(data1-data2)
print(data1*data2)
print(data1/data2)
print(data1%data2)
print(data1//data2)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [41]:
data1 = np.array([ [1, 2], [3, 4], [5, 6] ])
print("data1", data1, data1.shape, "\n")
print(data1 + 1, "\n")
data2 = np.array([ [1], [2], [3] ])
print("data2", data2, data2.shape, "\n")
print(data1 + data2, "\n")
data3 = np.array([ [1, 2, 3] ])
print("data3", data3, data3.shape, "\n")
print(data2 + data3, "\n")
# numpy의 브로드캐스팅

data1 [[1 2]
 [3 4]
 [5 6]] (3, 2) 

[[2 3]
 [4 5]
 [6 7]] 

data2 [[1]
 [2]
 [3]] (3, 1) 

[[2 3]
 [5 6]
 [8 9]] 

data3 [[1 2 3]] (1, 3) 

[[2 3 4]
 [3 4 5]
 [4 5 6]] 



In [43]:
data1 = np.random.randn(3, 2)
data2 = np.random.randn(2, 3)
data1 @ data2
# 행렬 곱셈

array([[ 1.46173123, -1.5163977 ,  0.57682774],
       [-2.17808612,  2.93940464, -0.85004797],
       [-4.89817783,  2.37872632, -1.97055239]])

In [45]:
data3 = np.array([ [1., 2., 3.], [4., 5., 6.] ])
print(data3)
print(data3[1, 1])
print(data3[:, 1])
print(data3[:, :])
print(data3[:1, :2])
# 행렬의 인덱싱

[[1. 2. 3.]
 [4. 5. 6.]]
5.0
[2. 5.]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2.]]


In [48]:
data1 = np.array([ [1, 2, 3], [4, 5, 6] ])
data2 = data1 > 3
print(data2)
print(data1[data2])
print(data1[(data1 > 3) & (data1 < 5)])
# boolean 인덱싱

[[False False False]
 [ True  True  True]]
[4 5 6]
[4]


In [53]:
data1 = np.random.randn(4, 3)
print(data1)

print(data1[ [1, 0, 2] ])
print(data1[ [1, -1] ])

print(data1[ [1, 2] ][:, [0, 2] ])
print(data1[ [1, -1] ][:, [0] ])
# fancy 인덱싱(특정 행과 열 추출하기)

[[-0.23022912 -0.59473899 -2.14727632]
 [ 0.52874172 -0.07772152  0.02034885]
 [-0.51479158  0.8017621   0.97727277]
 [ 0.43945113  0.42715954 -0.55637387]]
[[ 0.52874172 -0.07772152  0.02034885]
 [-0.23022912 -0.59473899 -2.14727632]
 [-0.51479158  0.8017621   0.97727277]]
[[ 0.52874172 -0.07772152  0.02034885]
 [ 0.43945113  0.42715954 -0.55637387]]
[[ 0.52874172  0.02034885]
 [-0.51479158  0.97727277]]
[[0.52874172]
 [0.43945113]]


In [60]:
data1 = np.array([ [1, 2, 3], [4, 5, 6] ])
print(data1)
data2 = data1[:2, :2]
print(data2)

# data2[1, 1] = 4
print(data2)
print(data1)
# 얉은 복사

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [61]:
data3 = data1[:2, :2].copy()
print(data3)
data3[1, 1] = 4
print(data3)
print(data1)
# 깊은 복사

[[1 2]
 [4 5]]
[[1 2]
 [4 4]]
[[1 2 3]
 [4 5 6]]


In [63]:
data1 = np.array([7, 5, 5, 4, 1])
index = np.where(data1 < 3)
print(index)
print(data1[index])
# 조건에 맞는 값 인덱싱

(array([4], dtype=int64),)
[1]


In [65]:
print(data1)
data2 = np.where(data1 < 3, -1, 1)
print(data2)
# 조건에 맞으면 -1, 틀리면 1로 값을 수정

[7 5 5 4 1]
[ 1  1  1  1 -1]


In [66]:
data1 = np.array([ [1, 2, 3], [4, 5, 6] ])
data2 = np.where(data1 < 3, -1, 1)
print(data2)

[[-1 -1  1]
 [ 1  1  1]]


In [67]:
data1 = np.array([ [1, 2, 3], [4, 5, 6] ])
print(data1.min())
print(data1.max())
print(data1.sum())
print(data1.mean())
print(data1.var())
print(data1.std())
print(data1.argmin())
print(data1.argmax())

1
6
21
3.5
2.9166666666666665
1.707825127659933
0
5


In [71]:
data1 = np.linspace(1, 5, 4)
print(data1)
# np.save('mydata1', data1)

# data2 = np.load('mydata1.npy')

data2 = np.linspace(1, 5, 4)
data3 = np.linspace(1, 10, 4)
data4 = np.linspace(1, 100, 4)
print(data2)
print(data3)
print(data4)
# np.savez('mydatas', five=data2, ten=data2, hundred=data3)

# datas = np.load('mydatas.npz')
# print(datas.files)
# print(datas['five'])
# print(datas['ten'])
# print(datas['hundred'])

[1.         2.33333333 3.66666667 5.        ]
[1.         2.33333333 3.66666667 5.        ]
[ 1.  4.  7. 10.]
[  1.  34.  67. 100.]
