In [1]:
import torch

torch.__version__

'2.5.1'

In [5]:
import numpy as np
data1 = np.array(10)
print(data1, data1.ndim, data1.shape)

10 0 ()


In [7]:
data1 = torch.FloatTensor([1, 2])
print(data1, data1.dim(), data1.shape)

data2 = torch.FloatTensor(3)
print(data2, data2.dim(), data2.shape)

tensor([1., 2.]) 1 torch.Size([2])
tensor([0., 0., 0.]) 1 torch.Size([3])


In [11]:
data3 = torch.FloatTensor(3, 2)
print(data3, data3.dim(), data3.shape)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) 2 torch.Size([3, 2])


In [18]:
data4 = torch.FloatTensor(3, 2, 1)
print(data4, data4.dim(), data4.shape)

tensor([[[-8.9356e+12],
         [ 2.0165e-42]],

        [[ 0.0000e+00],
         [ 0.0000e+00]],

        [[ 0.0000e+00],
         [ 0.0000e+00]]]) 3 torch.Size([3, 2, 1])


In [19]:
data5 = torch.FloatTensor([[1],[2],[3]])
print(data5, data5.dim(), data5.shape)

data6 = torch.FloatTensor([[1, 2, 3]])
print(data6, data6.dim(), data6.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
tensor([[1., 2., 3.]]) 2 torch.Size([1, 3])


In [6]:
import torch

data1 = torch.zeros(2, dtype=torch.float)
data2 = torch.ones(2, 2, dtype=torch.double)
data3 = torch.rand(2, 2, 3, dtype=torch.half)

print(data1.shape, data2.shape, data3.shape)

torch.Size([2]) torch.Size([2, 2]) torch.Size([2, 2, 3])


In [10]:
print(data1, data1.dim(), data1.shape, data1.dtype)
print(data2, data2.dim(), data2.shape, data2.dtype)
print(data3, data3.dim(), data3.shape, data3.dtype)

tensor([0., 0.]) 1 torch.Size([2]) torch.float32
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64) 2 torch.Size([2, 2]) torch.float64
tensor([[[0.7109, 0.3125, 0.1650],
         [0.6377, 0.9326, 0.3433]],

        [[0.4341, 0.2222, 0.3828],
         [0.7241, 0.6865, 0.4805]]], dtype=torch.float16) 3 torch.Size([2, 2, 3]) torch.float16


In [13]:
data1 = torch.DoubleTensor([[1, 2, 3], [4, 5, 6]])
print(data1, data1.shape)
data1 = data1.reshape(3, 2)
print(data1, data1.shape)
data1 = data1.reshape(2, -1)
print(data1, data1.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) torch.Size([2, 3])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64) torch.Size([3, 2])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) torch.Size([2, 3])


In [17]:
data1 = torch.DoubleTensor(2, 2, 3)
print(data1, data1.shape)
data1 = data1.view(2, -1)
print(data1, data1.shape)

tensor([[[1.7301e-311,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]], dtype=torch.float64) torch.Size([2, 2, 3])
tensor([[1.7301e-311,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00]], dtype=torch.float64) torch.Size([2, 6])


In [18]:
data1 = torch.FloatTensor([[1], [2], [3]])
data2 = data1.squeeze()
print(data1, data1.dim(), data1.shape)
print(data2, data2.dim(), data2.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
tensor([1., 2., 3.]) 1 torch.Size([3])


In [19]:
data3 = torch.randn(2, 1, 3, 4)
data3.squeeze().shape

torch.Size([2, 3, 4])

In [20]:
data4 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(data4, data4.dim(), data4.shape)
data5 = data4.unsqueeze(0)
data6 = data4.unsqueeze(2)
print(data5, data5.dim(), data5.shape)
print(data6, data6.dim(), data6.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) 2 torch.Size([2, 3])
tensor([[[1., 2., 3.],
         [4., 5., 6.]]]) 3 torch.Size([1, 2, 3])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]]) 3 torch.Size([2, 3, 1])


In [4]:
import torch

data1 = torch.zeros(2, 2, dtype=torch.float)

data1 = data1.type(torch.int)
print(data1.dtype)

torch.int32


In [5]:
data1.T
print(data1)

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)


In [6]:
import numpy as np
data1 = np.array([[1, 2], [3, 4]])
print(data1, type(data1))
data2 = torch.from_numpy(data1)
print(data2, type(data2))
data3 = data2.numpy()
print(data3, type(data3))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [7]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [8]:
torch.arange(1, 6)

tensor([1, 2, 3, 4, 5])

In [9]:
torch.arange(2, 7, 2)

tensor([2, 4, 6])

In [13]:
torch.linspace(1, 5, 10)

tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])

In [8]:
data1 = torch.full((3, 2), 2)
data2 = torch.full((2, 3), 1)
print(data1)
print(data2)
torch.matmul(data1, data2)

tensor([[2, 2],
        [2, 2],
        [2, 2]])
tensor([[1, 1, 1],
        [1, 1, 1]])


tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [20]:
data3 = torch.full((2, 2), 2)
data4 = torch.full((2, 2), 3)
data3 * data4
# 행렬의 사칙연산(행렬곱 아님)은 shape이 동일해야함

tensor([[6, 6],
        [6, 6]])

In [1]:
data1 = torch.FloatTensor(10, 20, 4)
data2 = torch.FloatTensor(20, 4)
data3 = data1 + data2
print(data1.shape, data2.shape, data3.shape)

NameError: name 'torch' is not defined

In [3]:
import torch

In [12]:
data3 = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.] ])
print(data3)
print(data3[1, 1])
print(data3[:, :])
print(data3[:1, :2])
# 텐서 인덱싱(슬라이싱)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(5.)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.]])


In [18]:
data4 = torch.FloatTensor([ [1, 2, 3], [5, 5, 5] ])
data5 = data4 > 3
print(data5)
print(data4[data5])
print(data4[(data4 > 3) & (data4 < 6)])
# Boolean 인덱싱

tensor([[False, False, False],
        [ True,  True,  True]])
tensor([5., 5., 5.])
tensor([5., 5., 5.])


In [23]:
data1 = torch.randn(4, 3)
print(data1)

print(data1[ [1, 2, 0] ])
print(data1[ [1, -1] ])

print(data1[ [1, 2] ] [:, [0, 2] ])
print(data1[ [1, -1] ] [:, [0] ])
# Fancy 인덱싱(특정 행과 열 추출하기)

tensor([[-1.0968,  0.7614,  0.1990],
        [-0.3243,  0.3114, -0.5639],
        [ 0.7649,  0.1959, -0.0188],
        [ 0.2765,  0.3320, -0.5087]])
tensor([[-0.3243,  0.3114, -0.5639],
        [ 0.7649,  0.1959, -0.0188],
        [-1.0968,  0.7614,  0.1990]])
tensor([[-0.3243,  0.3114, -0.5639],
        [ 0.2765,  0.3320, -0.5087]])
tensor([[-0.3243, -0.5639],
        [ 0.7649, -0.0188]])
tensor([[-0.3243],
        [ 0.2765]])


In [3]:
data1 = torch.FloatTensor([ [1, 2, 3], [4, 5, 6] ])
print(data1)
data2 = data1[:2, :2]
print(data2)

# 얕은 복사
# data2[1, 1] = 4
print(data2)
print(data1)

# 깊은 복사
data2 = data1[:2, :2].clone().detach()
print(data2)
data2[1, 1] = 4
print(data2)
print(data1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[1., 2.],
        [4., 4.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [5]:
import torch

data1 = torch.FloatTensor([7, 2, 0, 4, 1])
index = torch.where(data1 < 3)
print(index)
print(data1[index])
# 조건에 맞는 인덱스 번호 리턴

(tensor([1, 2, 4]),)
tensor([2., 0., 1.])


In [6]:
print(data1)
data2 = torch.where(data1 < 3, -1, 1)
print(data2)
# 조건에 맞으면 -1, 틀리면 1로 원소 값을 수정

tensor([7., 2., 0., 4., 1.])
tensor([ 1, -1, -1,  1, -1])


In [9]:
data1 = torch.FloatTensor([ [1, 2, 3], [4, 5, 6] ])
data2 = torch.where(data1 < 3, -1, 1)
print(data2)
# 다차원 배열에도 사용가능

tensor([[-1, -1,  1],
        [ 1,  1,  1]])


In [11]:
data1 = torch.FloatTensor([ [1, 2, 3], [4, 5, 6] ])
print(data1.min())
print(data1.max())
print(data1.sum())
print(data1.mean()) # 평균
print(data1.var()) # 분산
print(data1.std()) # 표준편차
print(data1.argmin()) # 최소값의 인덱스 번호
print(data1.argmax()) # 최대값의 인덱스 번호

tensor(1.)
tensor(6.)
tensor(21.)
tensor(3.5000)
tensor(3.5000)
tensor(1.8708)
tensor(0)
tensor(5)


In [13]:
data1 = torch.linspace(1, 5, 4)
print(data1)
torch.save(data1, 'mydata1.pt')

tensor([1.0000, 2.3333, 3.6667, 5.0000])


In [16]:
data2 = torch.load('mydata1.pt')
print(data2)

tensor([1.0000, 2.3333, 3.6667, 5.0000])


C:\Users\JHN\AppData\Local\Temp\ipykernel_10364\3979789577.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data2 = torch.load('mydata1.pt')


In [18]:
data1 = torch.linspace(1, 5, 4)
data2 = torch.linspace(1, 10, 4)
data3 = torch.linspace(1, 100, 4)
print(data1)
print(data2)
print(data3)
datas = {'data1': data1, 'data2': data2, 'data3': data3}
torch.save(datas, 'mydata1.pt')

tensor([1.0000, 2.3333, 3.6667, 5.0000])
tensor([ 1.,  4.,  7., 10.])
tensor([  1.,  34.,  67., 100.])


In [19]:
datas = torch.load('mydata1.pt')
print(datas['data1'])
print(datas['data2'])
print(datas['data3'])

tensor([1.0000, 2.3333, 3.6667, 5.0000])
tensor([ 1.,  4.,  7., 10.])
tensor([  1.,  34.,  67., 100.])


C:\Users\JHN\AppData\Local\Temp\ipykernel_10364\1106376832.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  datas = torch.load('mydata1.pt')
